LIST (APPEND algorithm_SOURCES
    src/algorithm/bucket_method/k_th_number.cc
    src/algorithm/bucket_method/range_minimum_query.cc
    src/algorithm/dynamic_programming/longest_increasing_subsequence/longest_increasing_subsequence.cc
    src/algorithm/dynamic_programming/traveling_by_stagecoach.cc
    src/algorithm/dynamic_programming/traveling_salesman_problem.cc
    src/algorithm/graph/bellman_ford/bellman_ford.cc
    src/algorithm/graph/bipartite_graph/bipartite_graph.cc
    src/algorithm/graph/dijkstra/dijkstra.cc
    src/algorithm/graph/ford_fulkerson.cc
    src/algorithm/graph/graph.cc
    src/algorithm/graph/minimum_spanning_tree/kruskal.cc
    src/algorithm/graph/warshall_floyd/warshall_floyd.cc
    src/algorithm/knapsack/knapsack.cc
    src/algorithm/segment_tree/a_simple_problem_with_integers.cc
    src/algorithm/segment_tree/binary_index_tree.cc
    src/algorithm/segment_tree/crane.cc
    src/algorithm/segment_tree/range_minimum_query.cc
    src/algorithm/segment_tree/solve_count_bubble_sort.cc
)
LIST (APPEND algorithm_HEADERS
    src/algorithm/bucket_method/k_th_number.h
    src/algorithm/bucket_method/range_minimum_query.h
    src/algorithm/dynamic_programming/longest_increasing_subsequence/longest_increasing_subsequence.h
    src/algorithm/dynamic_programming/traveling_by_stagecoach.h
    src/algorithm/dynamic_programming/traveling_salesman_problem.h
    src/algorithm/graph/bellman_ford/bellman_ford.h
    src/algorithm/graph/bipartite_graph/bipartite_graph.h
    src/algorithm/graph/dijkstra/dijkstra.h
    src/algorithm/graph/ford_fulkerson.h
    src/algorithm/graph/graph.h
    src/algorithm/graph/minimum_spanning_tree/kruskal.h
    src/algorithm/graph/warshall_floyd/warshall_floyd.h
    src/algorithm/knapsack/knapsack.h
    src/algorithm/segment_tree/a_simple_problem_with_integers.h
    src/algorithm/segment_tree/binary_index_tree.h
    src/algorithm/segment_tree/crane.h
    src/algorithm/segment_tree/range_minimum_query.h
    src/algorithm/segment_tree/solve_count_bubble_sort.h
)

