LIST (APPEND chap2_SOURCES
    src/chap2/breadth_first_search.cc
    src/chap2/depth_first_search.cc
    src/chap2/factorial.cc
    src/chap2/fence_repair.cc
    src/chap2/greedy_best_cow_line.cc
    src/chap2/greedy_coin.cc
    src/chap2/greedy_scheduling.cc
    src/chap2/knapsack.cc
    src/chap2/knapsack_with_duplication.cc
    src/chap2/lake_counting.cc
    src/chap2/longest_common_subsequence.cc
    src/chap2/partial_sum.cc
    src/chap2/saruman_army.cc
)
LIST (APPEND chap2_HEADERS
    src/chap2/breadth_first_search.h
    src/chap2/depth_first_search.h
    src/chap2/factorial.h
    src/chap2/fence_repair.h
    src/chap2/greedy_best_cow_line.h
    src/chap2/greedy_coin.h
    src/chap2/greedy_scheduling.h
    src/chap2/knapsack.h
    src/chap2/knapsack_with_duplication.h
    src/chap2/lake_counting.h
    src/chap2/longest_common_subsequence.h
    src/chap2/partial_sum.h
    src/chap2/saruman_army.h
)
