LIST (APPEND chap2_test_SOURCES
    src/pccb/chap2/bellman_ford_test.cc
    src/pccb/chap2/binary_search_tree_test.cc
    src/pccb/chap2/bipartite_graph_test.cc
    src/pccb/chap2/breadth_first_search_test.cc
    src/pccb/chap2/gcj/bribe_the_prisoners_test.cc
    src/pccb/chap2/crazy_rows_test.cc
    src/pccb/chap2/depth_first_search_test.cc
    src/pccb/chap2/dijkstra_test.cc
    src/pccb/chap2/factorial_test.cc
    src/pccb/chap2/fence_repair_test.cc
    src/pccb/chap2/greedy_best_cow_line_test.cc
    src/pccb/chap2/greedy_coin_test.cc
    src/pccb/chap2/greedy_scheduling_test.cc
    src/pccb/chap2/knapsack2_test.cc
    src/pccb/chap2/knapsack_test.cc
    src/pccb/chap2/knapsack_with_duplication_test.cc
    src/pccb/chap2/lake_counting_test.cc
    src/pccb/chap2/longest_common_subsequence_test.cc
    src/pccb/chap2/main.cc
    src/pccb/chap2/minimum_scalar_product_test.cc
    src/pccb/chap2/minimum_spanning_tree/conscription_test.cc
    src/pccb/chap2/minimum_spanning_tree/minimum_spanning_tree_test.cc
    src/pccb/chap2/minimum_spanning_tree/roadblocks_test.cc
    src/pccb/chap2/number_of_combination/number_of_combination_test.cc
    src/pccb/chap2/number_of_partitioning_pattern/number_of_partitioning_pattern_test.cc
    src/pccb/chap2/partial_sum_test.cc
    src/pccb/chap2/prime_number_test.cc
    src/pccb/chap2/saruman_army_test.cc
    src/pccb/chap2/union_find_tree_test.cc
    src/pccb/chap2/warshall_floyd_test.cc
)
