LIST (APPEND chap2_SOURCES
    src/chap2/bellman_ford.cc
    src/chap2/binary_search_tree.cc
    src/chap2/bipartite_graph.cc
    src/chap2/breadth_first_search.cc
    src/chap2/gcj/bribe_the_prisoners.cc
    src/chap2/crazy_rows.cc
    src/chap2/depth_first_search.cc
    src/chap2/dijkstra.cc
    src/chap2/factorial.cc
    src/chap2/fence_repair.cc
    src/chap2/greedy_best_cow_line.cc
    src/chap2/greedy_coin.cc
    src/chap2/greedy_scheduling.cc
    src/chap2/knapsack.cc
    src/chap2/knapsack2.cc
    src/chap2/knapsack_with_duplication.cc
    src/chap2/lake_counting.cc
    src/chap2/longest_common_subsequence.cc
    src/chap2/longest_increasing_subsequence/longest_increasing_subsequence.cc
    src/chap2/minimum_scalar_product.cc
    src/chap2/minimum_spanning_tree/conscription.cc
    src/chap2/minimum_spanning_tree/minimum_spanning_tree.cc
    src/chap2/minimum_spanning_tree/roadblocks.cc
    src/chap2/number_of_combination/number_of_combination.cc
    src/chap2/number_of_partitioning_pattern/number_of_partitioning_pattern.cc
    src/chap2/partial_sum.cc
    src/chap2/prime_number.cc
    src/chap2/saruman_army.cc
    src/chap2/union_find_tree.cc
    src/chap2/warshall_floyd.cc
)
LIST (APPEND chap2_HEADERS
    src/chap2/bellman_ford.h
    src/chap2/binary_search_tree.h
    src/chap2/bipartite_graph.h
    src/chap2/breadth_first_search.h
    src/chap2/gcj/bribe_the_prisoners.h
    src/chap2/crazy_rows.h
    src/chap2/depth_first_search.h
    src/chap2/dijkstra.h
    src/chap2/factorial.h
    src/chap2/fence_repair.h
    src/chap2/greedy_best_cow_line.h
    src/chap2/greedy_coin.h
    src/chap2/greedy_scheduling.h
    src/chap2/gtest_helper.h
    src/chap2/knapsack.h
    src/chap2/knapsack2.h
    src/chap2/knapsack_with_duplication.h
    src/chap2/lake_counting.h
    src/chap2/longest_common_subsequence.h
    src/chap2/longest_increasing_subsequence/longest_increasing_subsequence.h
    src/chap2/minimum_scalar_product.h
    src/chap2/minimum_spanning_tree/conscription.h
    src/chap2/minimum_spanning_tree/minimum_spanning_tree.h
    src/chap2/minimum_spanning_tree/roadblocks.h
    src/chap2/number_of_combination/number_of_combination.h
    src/chap2/number_of_partitioning_pattern/number_of_partitioning_pattern.h
    src/chap2/partial_sum.h
    src/chap2/prime_number.h
    src/chap2/saruman_army.h
    src/chap2/union_find_tree.h
    src/chap2/warshall_floyd.h
)
